use crate::registry::Registry;
use anyhow::{Context, Result};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use tracing::info;

/// The post-push hook script template.
///
/// Placeholders:
///   {task_master_bin}  – absolute path to the task-master binary
///   {worktree_name}    – e.g. "WIS-olive"
const HOOK_TEMPLATE: &str = r#"#!/usr/bin/env bash
# Auto-generated by task-master install-qa-hooks
# Spawns a QA agent whenever a branch with an open PR is pushed.
set -euo pipefail

TASK_MASTER="{task_master_bin}"
WORKTREE="{worktree_name}"

# Only act on normal branch pushes (not tag pushes, not deletions).
while read -r local_ref local_sha remote_ref remote_sha; do
    # Skip deletions (zero sha)
    if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
        continue
    fi

    # Extract branch name from refs/heads/branch-name
    branch="${{remote_ref#refs/heads/}}"
    if [ "$branch" = "$remote_ref" ]; then
        # Not a branch ref, skip
        continue
    fi

    # Check if there's an open PR for this branch (requires gh CLI)
    if ! command -v gh &>/dev/null; then
        echo "[task-master qa] gh CLI not found, skipping QA agent spawn." >&2
        continue
    fi

    pr_number=$(gh pr view "$branch" --json number --jq '.number' 2>/dev/null || true)

    if [ -z "$pr_number" ]; then
        echo "[task-master qa] No open PR found for branch '$branch', skipping." >&2
        continue
    fi

    echo "[task-master qa] PR #$pr_number detected for branch '$branch'. Spawning QA agent..."

    # Spawn non-blocking — the hook must not block git push.
    nohup "$TASK_MASTER" qa "$WORKTREE" "$pr_number" </dev/null >/tmp/task-master-qa-$pr_number.log 2>&1 &

    echo "[task-master qa] QA agent spawned (log: /tmp/task-master-qa-$pr_number.log)"
done
"#;

/// Install the post-push QA hook into the git directory of the given worktree path.
fn install_hook_for_worktree(
    worktree_path: &PathBuf,
    worktree_name: &str,
    task_master_bin: &str,
) -> Result<()> {
    // For a git worktree the hooks live in the *main* repo's .git/hooks, not
    // in the worktree's .git file. But for bare repos used as worktree bases the
    // hooks dir is directly inside the bare repo. We handle both cases by
    // asking git where the common dir is.
    let common_dir = git_common_dir(worktree_path)?;
    let hooks_dir = PathBuf::from(&common_dir).join("hooks");

    fs::create_dir_all(&hooks_dir)
        .with_context(|| format!("Failed to create hooks dir: {}", hooks_dir.display()))?;

    let hook_path = hooks_dir.join("post-push");

    let script = HOOK_TEMPLATE
        .replace("{task_master_bin}", task_master_bin)
        .replace("{worktree_name}", worktree_name);

    fs::write(&hook_path, &script)
        .with_context(|| format!("Failed to write hook: {}", hook_path.display()))?;

    // Make executable: rwxr-xr-x
    fs::set_permissions(&hook_path, fs::Permissions::from_mode(0o755))
        .with_context(|| format!("Failed to chmod hook: {}", hook_path.display()))?;

    info!(
        "[{}] Installed post-push hook at {}",
        worktree_name,
        hook_path.display()
    );
    println!(
        "  [{}] post-push hook -> {}",
        worktree_name,
        hook_path.display()
    );

    Ok(())
}

fn git_common_dir(worktree_path: &PathBuf) -> Result<String> {
    let output = std::process::Command::new("git")
        .args([
            "-C",
            &worktree_path.to_string_lossy(),
            "rev-parse",
            "--git-common-dir",
        ])
        .output()
        .context("Failed to run git rev-parse --git-common-dir")?;

    if !output.status.success() {
        anyhow::bail!(
            "git rev-parse --git-common-dir failed in {}",
            worktree_path.display()
        );
    }

    let raw = String::from_utf8_lossy(&output.stdout).trim().to_string();

    // The output may be relative to the worktree dir; canonicalize it.
    let path = if std::path::Path::new(&raw).is_absolute() {
        PathBuf::from(raw)
    } else {
        worktree_path.join(&raw)
    };

    path.canonicalize()
        .map(|p| p.to_string_lossy().to_string())
        .with_context(|| format!("Failed to canonicalize git common dir: {}", path.display()))
}

/// Resolve the path to the currently running task-master binary.
fn current_binary() -> Result<String> {
    std::env::current_exe()
        .context("Failed to determine current executable path")?
        .canonicalize()
        .context("Failed to canonicalize executable path")
        .map(|p| p.to_string_lossy().to_string())
}

/// Install QA post-push hooks into every registered worktree.
pub fn cmd_install_qa_hooks(registry: &Registry) -> Result<()> {
    let bin = current_binary()?;

    println!("Installing QA post-push hooks (binary: {}):", bin);

    let mut count = 0;
    for wt in &registry.worktrees {
        if !wt.abs_path.exists() {
            println!(
                "  [{}] skipped (worktree directory does not exist: {})",
                wt.window_name,
                wt.abs_path.display()
            );
            continue;
        }
        install_hook_for_worktree(&wt.abs_path, &wt.window_name, &bin)?;
        count += 1;
    }

    println!("\nDone. Installed hooks in {} worktree(s).", count);
    println!("Remember: when agents open a PR they should add the 'wip' label:");
    println!("  gh pr create --label wip ...");

    Ok(())
}

/// Install QA post-push hook for a single worktree (called from add-worktree).
pub fn install_hook_for_single(worktree_path: &PathBuf, worktree_name: &str) -> Result<()> {
    let bin = current_binary()?;
    install_hook_for_worktree(worktree_path, worktree_name, &bin)
}
