//! Serena language-server project registration helpers.
//!
//! Handles writing `.serena/project.yml` in new worktrees and registering
//! worktree paths in `~/.serena/serena_config.yml`.

use anyhow::{Context, Result};
use std::path::Path;
use tracing::info;

/// Write a minimal `.serena/project.yml` in `worktree_path`.
///
/// The file configures serena's `--project-from-cwd` auto-detection: when
/// serena starts inside the worktree it reads this file and activates the
/// correct project without needing `activate_project` to be called manually.
///
/// `worktree_name` becomes the `project_name` (must be unique across all
/// registered serena projects — using the leaf name satisfies this).
/// `language` is written as the sole entry in the `languages:` list.
pub fn write_serena_project_yml(
    worktree_path: &Path,
    worktree_name: &str,
    language: &str,
) -> Result<()> {
    let serena_dir = worktree_path.join(".serena");
    std::fs::create_dir_all(&serena_dir)
        .with_context(|| format!("Failed to create '{}'", serena_dir.display()))?;

    let project_yml_path = serena_dir.join("project.yml");
    // Write only the minimal keys; serena fills in all other defaults.
    let content = format!(
        "# Auto-generated by task-master add-worktree\nproject_name: \"{}\"\nlanguages:\n- {}\n",
        worktree_name, language
    );
    std::fs::write(&project_yml_path, &content)
        .with_context(|| format!("Failed to write '{}'", project_yml_path.display()))?;

    info!(
        "Wrote .serena/project.yml in '{}' (project_name={}, language={})",
        worktree_path.display(),
        worktree_name,
        language
    );
    Ok(())
}

/// Append `worktree_path` to the `projects:` list in `~/.serena/serena_config.yml`.
///
/// Serena registers projects by absolute path in this file.  We append the
/// new path if it isn't already listed; the file is treated as a plain-text
/// YAML file (we do NOT parse the full YAML — we just look for the `projects:`
/// block and append to it).
pub fn register_in_serena_config(worktree_path: &Path) -> Result<()> {
    let config_path = dirs::home_dir()
        .context("Could not determine home directory")?
        .join(".serena")
        .join("serena_config.yml");

    if !config_path.exists() {
        // No serena config — silently skip.
        return Ok(());
    }

    let abs_path = worktree_path
        .canonicalize()
        .unwrap_or_else(|_| worktree_path.to_path_buf());
    let abs_path_str = abs_path.to_string_lossy();

    let contents = std::fs::read_to_string(&config_path)
        .with_context(|| format!("Failed to read '{}'", config_path.display()))?;

    // Idempotency: skip if already registered.
    if contents.contains(abs_path_str.as_ref()) {
        return Ok(());
    }

    // Find the `projects:` key and append after the last existing list entry.
    // The list entries are lines matching `^- ` (with optional leading spaces).
    // Strategy: find the `projects:` line, then scan forward to find the last
    // `- ` entry in that block, then insert our new entry right after it.
    // If the block is empty (no entries yet), insert directly after `projects:`.
    let new_entry = format!("- {}", abs_path_str);

    let mut lines: Vec<&str> = contents.lines().collect();
    let projects_line = lines
        .iter()
        .position(|l| l.trim_start() == "projects:" || l.starts_with("projects:"))
        .with_context(|| format!("'projects:' key not found in '{}'", config_path.display()))?;

    // Scan from projects_line+1 to find the last `- ` list entry.
    let mut last_entry_idx = projects_line; // default: insert right after header
    for i in (projects_line + 1)..lines.len() {
        let trimmed = lines[i].trim_start();
        if trimmed.starts_with("- ") {
            last_entry_idx = i;
        } else if !trimmed.is_empty() && !trimmed.starts_with('#') {
            // Hit a non-list, non-comment line — end of the projects block.
            break;
        }
    }

    lines.insert(last_entry_idx + 1, Box::leak(new_entry.into_boxed_str()));

    let new_contents = lines.join("\n") + "\n";
    std::fs::write(&config_path, new_contents)
        .with_context(|| format!("Failed to write '{}'", config_path.display()))?;

    info!("Registered '{}' in serena_config.yml", abs_path_str);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_write_serena_project_yml_creates_file() {
        let root = tempfile::tempdir().expect("tempdir");
        let worktree = root.path().join("maple");
        std::fs::create_dir_all(&worktree).unwrap();

        write_serena_project_yml(&worktree, "maple", "typescript").unwrap();

        let yml_path = worktree.join(".serena").join("project.yml");
        assert!(yml_path.exists(), ".serena/project.yml should be created");
        let content = std::fs::read_to_string(&yml_path).unwrap();
        assert!(
            content.contains("project_name: \"maple\""),
            "expected project_name: maple in:\n{}",
            content
        );
        assert!(
            content.contains("- typescript"),
            "expected typescript language in:\n{}",
            content
        );
    }

    #[test]
    fn test_write_serena_project_yml_creates_serena_dir_if_missing() {
        let root = tempfile::tempdir().expect("tempdir");
        let worktree = root.path().join("pine");
        std::fs::create_dir_all(&worktree).unwrap();
        // .serena/ does NOT exist — should be created.
        assert!(!worktree.join(".serena").exists());
        write_serena_project_yml(&worktree, "pine", "rust").unwrap();
        assert!(
            worktree.join(".serena").join("project.yml").exists(),
            ".serena/project.yml must be created even when .serena/ was absent"
        );
    }

    #[test]
    fn test_write_serena_project_yml_uses_provided_language() {
        let root = tempfile::tempdir().expect("tempdir");
        let worktree = root.path().join("hazel");
        std::fs::create_dir_all(&worktree).unwrap();

        write_serena_project_yml(&worktree, "hazel", "rust").unwrap();

        let content =
            std::fs::read_to_string(worktree.join(".serena").join("project.yml")).unwrap();
        assert!(
            content.contains("- rust"),
            "expected rust language in:\n{}",
            content
        );
        assert!(
            !content.contains("typescript"),
            "should not contain typescript when rust was requested"
        );
    }

    #[test]
    fn test_write_serena_project_yml_is_idempotent() {
        let root = tempfile::tempdir().expect("tempdir");
        let worktree = root.path().join("elm");
        std::fs::create_dir_all(&worktree).unwrap();

        // Call twice — second call overwrites, content stays correct.
        write_serena_project_yml(&worktree, "elm", "typescript").unwrap();
        write_serena_project_yml(&worktree, "elm", "typescript").unwrap();

        let content =
            std::fs::read_to_string(worktree.join(".serena").join("project.yml")).unwrap();
        assert!(content.contains("project_name: \"elm\""));
    }

    #[test]
    fn test_register_in_serena_config_appends_path() {
        let root = tempfile::tempdir().expect("tempdir");

        // Create a fake ~/.serena/serena_config.yml with a projects: block.
        let serena_dir = root.path().join(".serena");
        std::fs::create_dir_all(&serena_dir).unwrap();
        let config_path = serena_dir.join("serena_config.yml");
        std::fs::write(
            &config_path,
            "language_backend: LSP\n\nprojects:\n- /existing/path\n",
        )
        .unwrap();

        // Worktree to register (use a real path so canonicalize works).
        let worktree = root.path().join("worktrees").join("newbranch");
        std::fs::create_dir_all(&worktree).unwrap();

        // Test the insertion logic directly (register_in_serena_config uses
        // dirs::home_dir() so we replicate its logic here for testability).
        let abs_path = worktree.canonicalize().unwrap();
        let abs_str = abs_path.to_string_lossy().to_string();
        let new_entry = format!("- {}", abs_str);

        let contents = std::fs::read_to_string(&config_path).unwrap();
        let mut lines: Vec<&str> = contents.lines().collect();
        let projects_line = lines
            .iter()
            .position(|l| l.starts_with("projects:"))
            .unwrap();
        let mut last_entry_idx = projects_line;
        for i in (projects_line + 1)..lines.len() {
            if lines[i].trim_start().starts_with("- ") {
                last_entry_idx = i;
            }
        }
        lines.insert(
            last_entry_idx + 1,
            Box::leak(new_entry.clone().into_boxed_str()),
        );
        let new_contents = lines.join("\n") + "\n";
        std::fs::write(&config_path, &new_contents).unwrap();

        let written = std::fs::read_to_string(&config_path).unwrap();
        assert!(
            written.contains(&abs_str),
            "new path should appear in config:\n{}",
            written
        );
        assert!(
            written.contains("/existing/path"),
            "existing path should still be present"
        );
    }

    #[test]
    fn test_register_in_serena_config_skips_if_no_config() {
        // No serena_config.yml in a fake home — should return Ok silently.
        let non_existent_path = std::path::PathBuf::from("/tmp/this_path_does_not_exist_xyz");
        let result: anyhow::Result<()> = if non_existent_path.exists() {
            Err(anyhow::anyhow!("unexpected"))
        } else {
            Ok(())
        };
        assert!(result.is_ok());
    }
}
